BEGIN;
--
-- Create model Posts
--
CREATE TABLE "posts_posts" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"title" varchar(128) NOT NULL,
"content" varchar(1024) NOT NULL,
"is_deleted" boolean NOT NULL,
"user_id" bigint NOT NULL);

ALTER TABLE "posts_posts" ADD CONSTRAINT "posts_posts_user_id_b88d85ff_fk_user_user_id"
FOREIGN KEY ("user_id") REFERENCES "user_user" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "posts_posts_user_id_b88d85ff" ON "posts_posts" ("user_id");
COMMIT;
