BEGIN;
--
-- Create model Comments
--
CREATE TABLE "comments_comments" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"comment" varchar(512) NOT NULL,
"is_deleted" boolean NOT NULL,
"parent_comment_id" bigint NULL,
"post_id" bigint NOT NULL,
"user_id" bigint NOT NULL
);

ALTER TABLE "comments_comments" ADD CONSTRAINT
"comments_comments_parent_comment_id_d58f072e_fk_comments_"
FOREIGN KEY ("parent_comment_id") REFERENCES "comments_comments" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comments_comments"
ADD CONSTRAINT "comments_comments_post_id_59c014a0_fk_posts_posts_id"
FOREIGN KEY ("post_id") REFERENCES "posts_posts" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "comments_comments"
ADD CONSTRAINT "comments_comments_user_id_d2c0ea69_fk_user_user_id"
FOREIGN KEY ("user_id") REFERENCES "user_user" ("id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "comments_comments_parent_comment_id_d58f072e" ON "comments_comments" ("parent_comment_id");

CREATE INDEX "comments_comments_post_id_59c014a0" ON "comments_comments" ("post_id");

CREATE INDEX "comments_comments_user_id_d2c0ea69" ON "comments_comments" ("user_id");

COMMIT;
