BEGIN;
--
-- Create model CommentLikes
--
CREATE TABLE "likes_commentlikes" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"comment_id" bigint NOT NULL,
"user_id" bigint NOT NULL,
CONSTRAINT "commentlikes_user_id_comment_id_unique_constraint"
UNIQUE ("user_id", "comment_id")
);
--
-- Create model PostLikes
--
CREATE TABLE "likes_postlikes" (
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"post_id" bigint NOT NULL,
"user_id" bigint NOT NULL,
CONSTRAINT "postlikes_user_id_post_id_unique_constraint"
UNIQUE ("user_id", "post_id"));

ALTER TABLE "likes_commentlikes" ADD CONSTRAINT
"likes_commentlikes_comment_id_9cb2d023_fk_comments_comments_id"
FOREIGN KEY ("comment_id") REFERENCES "comments_comments" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "likes_commentlikes" ADD CONSTRAINT
"likes_commentlikes_user_id_bd0f78c0_fk_user_user_id"
FOREIGN KEY ("user_id") REFERENCES "user_user" ("id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "likes_commentlikes_comment_id_9cb2d023" ON "likes_commentlikes" ("comment_id");

CREATE INDEX "likes_commentlikes_user_id_bd0f78c0" ON "likes_commentlikes" ("user_id");

ALTER TABLE "likes_postlikes" ADD CONSTRAINT
"likes_postlikes_post_id_c7f6d901_fk_posts_posts_id"
FOREIGN KEY ("post_id") REFERENCES "posts_posts" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "likes_postlikes" ADD CONSTRAINT
"likes_postlikes_user_id_f86cd290_fk_user_user_id"
FOREIGN KEY ("user_id") REFERENCES "user_user" ("id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "likes_postlikes_post_id_c7f6d901" ON "likes_postlikes" ("post_id");

CREATE INDEX "likes_postlikes_user_id_f86cd290" ON "likes_postlikes" ("user_id");
COMMIT;
