# Generated by Django 5.2 on 2025-04-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
