# Generated by Django 5.2 on 2025-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=256)),
                ('about', models.CharField(max_length=1024)),
                ('password', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
    ]
